---
title: "Food Prices"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
runtime: shiny
---

```{r setup, include=FALSE}
pacman::p_load(flexdashboard, here, tidyverse, shinyWidgets)

tidy_data <- readRDS(here("data", "tidy", "pricedata.rds"))
categories <- unique(tidy_data$category)
items <- unique(tidy_data$item)

```

Inputs {.sidebar}
======================================================================

### Inputs

```{r}

selectInput("categories", label = "Category", choices = categories)

pickerInput(inputId = "items",
            label = "Item",
            choices = items,
            multiple = TRUE,
            options = pickerOptions(actionsBox = TRUE)
              )

```

Charts
======================================================================
### Chart B

```{r}

plot_data <- reactive({

  tidy_data %>% 
  dplyr::filter(category == input$categories) 
    
})

renderPlot({ 
ggplot2::ggplot(data = plot_data(), aes(x = week, y = value, group = item, colour = item)) +
  geom_line() +
  geom_point() +
  facet_wrap(vars(item))
})

```

### Chart C

```{r}

item_plot_data <- reactive({

  tidy_data %>% 
  dplyr::filter(item %in% input$items) 
    
})

renderPlot({ 
ggplot2::ggplot(data = item_plot_data(), aes(x = week, y = value, group = item, colour = item)) +
  geom_line() +
  geom_point() +
  facet_wrap(vars(item))
})




```

